/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Triple {
  subject: string
  predicate: string
  object: string
}
export declare function inferTriples(tboxTtl: string, aboxTtl: string): Array<Triple>
